// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhOf3XM7UIf7TITZ-T-KC7FCRrUE_4ukM',
    appId: '1:475780052360:web:22ee3433fe482f059c763d',
    messagingSenderId: '475780052360',
    projectId: 'srestham-education-trust',
    authDomain: 'srestham-education-trust.firebaseapp.com',
    storageBucket: 'srestham-education-trust.appspot.com',
    measurementId: 'G-34Z6V0TBPE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOJHIhBM6JLCkKWqA7uZDm0KEISM9WdRw',
    appId: '1:475780052360:android:8c25a9a9c43e0aff9c763d',
    messagingSenderId: '475780052360',
    projectId: 'srestham-education-trust',
    storageBucket: 'srestham-education-trust.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQMmi7Uu5GMj4yhkmMKLnxaOHcV7V4LA0',
    appId: '1:475780052360:ios:910e4468c58dbe049c763d',
    messagingSenderId: '475780052360',
    projectId: 'srestham-education-trust',
    storageBucket: 'srestham-education-trust.appspot.com',
    iosBundleId: 'com.example.senderApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQMmi7Uu5GMj4yhkmMKLnxaOHcV7V4LA0',
    appId: '1:475780052360:ios:54c3f62ffa438aaa9c763d',
    messagingSenderId: '475780052360',
    projectId: 'srestham-education-trust',
    storageBucket: 'srestham-education-trust.appspot.com',
    iosBundleId: 'com.example.senderApp.RunnerTests',
  );
}
